### ISSUE TITLE
Stop hosting button is visible after the player quits a match.

### ISSUE THREAD

**Issue by peter-kish** [peter-kish/balls#18] opened 2015-11-21 09:43 UTC
The "Stop hosting" button is still visible after the player quits a match, even though his state is "idle". The Host/Stop hosting buttons should be reset every time the lobby is shown according to the player state.

**Comment by dziga** [comment] 2015-11-22 10:44
duplicate of #8

**Closed as completed** 2015-11-22 11:04 UTC
Labels: bug, fixed
